//Require modules
const express = require('express');
const careersRouter = require('./routes/careers');
const { Server } = require('mongodb');
const morgan = require('morgan');
const port = 3000


// Set up express app 
const app = express();

//Set up DB **- connecting to mongoose (8)
require('./config/database');

//Configure the view engine with app.set()
app.set('view engine', 'ejs')

//Mount middleware with app.use()
app.use(morgan('dev'));
app.use(express.static('public'));
app.use(express.urlencoded({extended: false}));


app.get('/', (req, res) => {
    const careers = [{
        title: "Data Science",
        description: "Every time you interact with a mobile app, use the internet, or visit a website data is generated. Every day large amounts of data are generated from millions of users, and nearly all of this data is valuable.  Understanding the data generated by customers leads to data-driven insights on products and services. As these swaths of data prove to be ever more useful to businesses, the demand for qualified professionals to handle and understand this data will only continue to grow."
    },
    {
        title: "Software Engineering",
        description: "Software engineering is the application of engineering concepts for software development. Its main goal is the creation, improvement, and maintenance of software. Software engineering takes into account engineering aspects like the hardware and software environment when working on a program."
    },
    {
        title: "User Experience/ User Interface (UX/UI) Design",
        description: "Behind every successful product is a designer who created the look and feel of the product. UX design is the process of designing how users will experience a product. They employ programming, visual design, usability testing, and psychology to craft a product that’s easy to use and navigate. UX designers accomplish this by thinking about the potential challenges customers may face with a product. They will also make changes to a design or feature based on their research to ensure customers can easily understand how to use a product."

    }]
    res.render('careers/index', { careers: careers });
})

// Mount routes with app.use()
app.use('/careers', careersRouter);


// Tell app to listen 
app.listen(port, function () {
    console.log(`Express is listening on port ${port}.`);
})



